[package]
name = "sop-fuzz"
version = "0.0.0"
publish = false
edition = "2024"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
serde_json = { version = "1", features = ["arbitrary_precision"] }

[dependencies.sop]
path = ".."

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
bench = false

[[bin]]
name = "json_superset"
path = "fuzz_targets/json_superset.rs"
test = false
doc = false
bench = false
